testing action update

diff --git a/.github/workflows/minishell_testing.yml b/.github/workflows/minishell_testing.yml
--- a/.github/workflows/minishell_testing.yml
+++ b/.github/workflows/minishell_testing.yml
@@ -20,22 +20,35 @@ jobs:
           
       - name: check for parsing code
         run: norminette srcs/parsing
+        continue-on-error: true
                 
       - name: check for builtin code
         run: norminette srcs/builtin
+        continue-on-error: true
               
       - name: check for signal code
         run: norminette srcs/signal
+        continue-on-error: true
                 
       - name: check for tree code
         run: norminette srcs/tree
+        continue-on-error: true
                 
       - name: check for utils code
         run: norminette srcs/utils
+        continue-on-error: true
                 
       - name: check for main code
         run: norminette srcs/minishell.c
+        continue-on-error: true
                 
+      - name: Fail job if any step failed
+        run: |
+          if [ -f ~/.errors ]; then
+            echo "Some steps failed. Marking job as failed."
+            exit 1
+          fi
+
   check_compile_error:
     runs-on: ubuntu-latest
     steps:
@@ -56,36 +69,37 @@ jobs:
           sudo apt install valgrind -y
           sudo apt-get install -y libreadline-dev
           make
+        continue-on-error: true               
           
       - name: testing "(cat A || echo 'x' > B) && (grep 'y' C | sort > D) || (echo 'c' >> E && ls -l)"
         run: |
-          echo "(cat A || echo 'x' > B) && (grep 'y' C | sort > D) || (echo 'c' >> E && ls -l)" |
+          echo "(cat A || echo \'x\' > B) && (grep \'y\' C | sort > D) || (echo \'c\' >> E && ls -l)" |
           valgrind --leak-check=full  ./minishell 
-          continue-on-error: true               
+        continue-on-error: true               
 
       - name: testing "(cat A || ls -a -l) && (grep "y" C| sort > D)"
         run: |
-          echo "(cat A || ls -a -l) && (grep 'y' C| sort > D)" |
+          echo "(cat A || ls -a -l) && (grep \'y\' C| sort > D)" |
           valgrind --leak-check=full  ./minishell 
-          continue-on-error: true               
+        continue-on-error: true               
                 
       - name: testing "'ls' >b | 'ls -al' >c <a"
         run: |
           echo "'ls' >b | 'ls -al' >c <a" |
           valgrind --leak-check=full  ./minishell 
-          continue-on-error: true               
+        continue-on-error: true               
         
       - name: testing "ls && ('(ls -al && "ls 3_Circle")' || ls 1_Circle)"
         run: |
           echo "ls && (\'(ls -al && \"ls 3_Circle\")\' || ls 1_Circle)" |
           valgrind --leak-check=full  ./minishell 
-          continue-on-error: true               
+        continue-on-error: true               
                 
       - name: testing "ls && ((ls -al && "ls 3_Circle") || ls 1_Circle)"
         run: |
           echo "ls && ((ls -al && \"ls 3_Circle\") || ls 1_Circle)" |
           valgrind --leak-check=full  ./minishell 
-          continue-on-error: true               
+        continue-on-error: true               
 
       - name: Fail job if any step failed
         run: |
